spring:
  datasource:
    username: jacplus
    password: Jacaranda2024@
    url: jdbc:mysql://localhost:3306/onlineLibrarydb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      rootcode:
        user_service: DEBUG